### ISSUE TITLE
1) User can login

### ISSUE THREAD

**Issue by shadorki** [uzair-ashraf/good-deed#1]
# User can login to dash board

### Task List

- [ ] Create user table inside good deed database as the same as the schema
https://app.dbdesigner.net/designer/schema/275753
- [ ] Create inital files through npm
- [ ] Add configure file to run development server
- [ ] create App.jsx for component folder
- [ ] create stateful header component to copy the first page of the figma
- [ ] create stateful login-page component to to take in login information of user
- [ ] create dummy data inside sql to match login information of first test user
- [ ] create login.php endpoint to send query to database with the data recieved from login page component
- [ ] add a method to app.jsx to connect to endpoint and create a fetch call
- [ ] add a this.setView state onto the app.jsx component
- [ ] create conditional to change the user view after the login query was succesful
- [ ] add conditional to state whether the login information was correct or not
