### ISSUE TITLE
2) User can view personal dash board

### ISSUE THREAD

**Issue by shadorki** [uzair-ashraf/good-deed#2]
# User can view personalized dash board

### Task List

- [ ] Create a stateful component called dashboard.jsx
- [ ] Pass the user data as a prop to the dashboard after login
- [ ] Add a conditional to setView to display the dashboard
- [ ] create users profile short display
- [ ] create container for users recent reviews
- [ ] create a stateful footer component called footer.jsx
- [ ] create five initital methods in app.jsx to pass in as props to footer.jsx for navigation.
- [ ] create navigation system and change callbacks based off which button is visible in the the state of the footer
